site_name: DB Semantic Layer
site_description: Abstraction and semantic layer for SQL databases with MCP
repo_url: https://example.com/repo
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - Concepts:
      - Architecture: concepts/architecture.md
      - Semantic layer: concepts/semantic-layer.md
      - MCP: concepts/mcp.md
  - Guides:
      - Configuring connections: guides/configuring-connections.md
      - NL to SQL: guides/nl-to-sql.md
      - Ontology generation: guides/ontology-generation.md
      - Security: guides/security.md
  - API: api/index.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search